[[plugins]]
repository = 'chaquotay/ftl-vim-syntax'

[[plugins]]
repository = 'vim-jp/vimdoc-ja'

[[plugins]]
repository = 'Shougo/neocomplcache'

[[plugins]]
repository = 'Shougo/unite.vim'

[[plugins]]
repository = 'Shougo/vimproc'

  [plugins.build]
    windows = 'tools\\update-dll-mingw'
    cygwin = 'make -f make_cygwin.mak'
    mac = 'make -f make_mac.mak'
    unix = 'make -f make_unix.mak'

[[plugins]]
repository = 'corntrace/bufexplorer'

[[plugins]]
repository = 'hrp/EnhancedCommentify'

[[plugins]]
repository = 'janx/vim-rubytest'

[[plugins]]
repository = 'kchmck/vim-coffee-script'

[[plugins]]
repository = 'mattn/webapi-vim'

[[plugins]]
repository = 'mileszs/ack.vim'

[[plugins]]
repository = 'msanders/cocoa.vim'

[[plugins]]
repository = 'plasticboy/vim-markdown'

[[plugins]]
repository = 'rgo/taglist.vim'

[[plugins]]
repository = 'scrooloose/nerdtree'

[[plugins]]
repository = 'scrooloose/syntastic'

[[plugins]]
repository = 'thinca/vim-qfreplace'

[[plugins]]
repository = 'thinca/vim-unite-history'

[[plugins]]
repository = 'thinca/vim-openbuf'

[[plugins]]
repository = 'tpope/vim-cucumber'

[[plugins]]
repository = 'tpope/vim-fugitive'

[[plugins]]
repository = 'tpope/vim-haml'

[[plugins]]
repository = 'tpope/vim-surround'

[[plugins]]
repository = 'tpope/vim-unimpaired'

[[plugins]]
repository = 'tpope/vim-abolish'

[[plugins]]
repository = 'tpope/vim-repeat'

[[plugins]]
repository = 'vim-ruby/vim-ruby'

[[plugins]]
repository = 'taku-o/vim-toggle'

[[plugins]]
repository = 'h1mesuke/unite-outline'

[[plugins]]
repository = 'h1mesuke/vim-alignta'

[[plugins]]
repository = 'ujihisa/unite-locate'

[[plugins]]
repository = 'ujihisa/unite-gem'

[[plugins]]
repository = 'ujihisa/shadow.vim'

[[plugins]]
repository = 'ujihisa/unite-rake'

[[plugins]]
repository = 'ujihisa/unite-colorscheme'

[[plugins]]
repository = 'tacroe/unite-mark'

[[plugins]]
repository = 'sgur/unite-qf'

[[plugins]]
repository = 'choplin/unite-vim_hacks'

[[plugins]]
repository = 'koron/chalice'

[[plugins]]
repository = 'tyru/open-browser.vim'

[[plugins]]
repository = 'hail2u/vim-css3-syntax'

[[plugins]]
repository = 'cakebaker/scss-syntax.vim'

[[plugins]]
repository = 'othree/html5.vim'

[[plugins]]
repository = 'kana/vim-textobj-user'

[[plugins]]
repository = 'kana/vim-textobj-indent'

[[plugins]]
repository = 'tsukkee/unite-tag'

[[plugins]]
repository = 'bitc/vim-bad-whitespace'

[[plugins]]
repository = 'petdance/vim-perl'

[[plugins]]
repository = 'pasela/unite-webcolorname'

[[plugins]]
repository = 'taichouchou2/alpaca_powertabline'

[[plugins]]
repository = 'Lokaltog/powerline'

[[plugins]]
repository = 'bling/vim-airline'

[[plugins]]
repository = 't9md/vim-surround_custom_mapping'

[[plugins]]
repository = 'einars/js-beautify'

[[plugins]]
repository = 'maksimr/vim-jsbeautify'

[[plugins]]
repository = 'nelstrom/vim-qargs'

[[plugins]]
repository = 'nelstrom/vim-visual-star-search'

[[plugins]]
repository = 'groenewege/vim-less'

[[plugins]]
repository = 'osyo-manga/vim-over'

[[plugins]]
repository = 'AndrewRadev/linediff.vim'

[[plugins]]
repository = 'martintreurnicht/vim-gradle.git'

[[plugins]]
repository = 'itchyny/calendar.vim'

[[plugins]]
repository = 'kannokanno/previm'

[[plugins]]
repository = 'tommcdo/vim-exchange'

[[plugins]]
repository = 'rizzatti/funcoo.vim'

[[plugins]]
repository = 'rizzatti/dash.vim'

[[plugins]]
repository = 'tejr/vim-tmux'

[[plugins]]
repository = 'altercation/vim-colors-solarized'

[[plugins]]
repository = 'rbtnn/rabbit-ui.vim'

[[plugins]]
repository = 'matchit.zip'

[[plugins]]
repository = 'JavaDecompiler.vim'

[[plugins]]
repository = 'SQLUtilities'

[[plugins]]
repository = 'svn-diff.vim'

[[plugins]]
repository = 'wombat256.vim'

[[plugins]]
repository = 'yanktmp.vim'

[[plugins]]
repository = 'perlcritic-compiler-script'

[[plugins]]
repository = 'Align'

[[plugins]]
repository = 'DirDiff.vim'

[[plugins]]
repository = 'vcscommand.vim'

