[[plugins]]
repository = 'Shougo/vimfiler'
explorer = 1
mappings = '<Plug>'

[[plugins]]
repository = 'thinca/vim-quickrun'

[[plugins]]
repository = 'Shougo/neosnippet'

[[plugins]]
repository = "Shougo/neosnippet-snippets"

[[plugins]]
repository = 'sjl/gundo.vim'

[[plugins]]
repository = 'rking/ag.vim'

[[plugins]]
repository = 'Shougo/vimshell'

[[plugins]]
repository = 'tpope/vim-endwise'
filetypes = 'ruby'

[[plugins]]
repository = 'tpope/vim-rails'
filetypes = 'ruby'

[[plugins]]
repository = 'thinca/vim-ref'
filetypes = 'ruby'

[[plugins]]
repository = 'mattn/emmet-vim'
filetypes = 'html'

# toml {{{
[[plugins]]
repository = 'cespare/vim-toml'
filetypes = 'toml'
