[[plugins]]
repo = 'chaquotay/ftl-vim-syntax'

[[plugins]]
repo = 'vim-jp/vimdoc-ja'

[[plugins]]
repo = 'Shougo/neocomplcache'

[[plugins]]
repo = 'Shougo/unite.vim'

[[plugins]]
repo = 'Shougo/vimproc'

  [plugins.build]
    windows = 'tools\\update-dll-mingw'
    cygwin = 'make -f make_cygwin.mak'
    mac = 'make -f make_mac.mak'
    unix = 'make -f make_unix.mak'

[[plugins]]
repo = 'corntrace/bufexplorer'

[[plugins]]
repo = 'hrp/EnhancedCommentify'

[[plugins]]
repo = 'kchmck/vim-coffee-script'

[[plugins]]
repo = 'mattn/webapi-vim'

[[plugins]]
repo = 'mileszs/ack.vim'

[[plugins]]
repo = 'msanders/cocoa.vim'

[[plugins]]
repo = 'plasticboy/vim-markdown'

[[plugins]]
repo = 'rgo/taglist.vim'

[[plugins]]
repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'scrooloose/syntastic'

[[plugins]]
repo = 'thinca/vim-qfreplace'

[[plugins]]
repo = 'thinca/vim-unite-history'

[[plugins]]
repo = 'thinca/vim-openbuf'

[[plugins]]
repo = 'tpope/vim-cucumber'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'tpope/vim-haml'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'tpope/vim-unimpaired'

[[plugins]]
repo = 'tpope/vim-abolish'

[[plugins]]
repo = 'tpope/vim-repeat'

[[plugins]]
repo = 'vim-ruby/vim-ruby'

[[plugins]]
repo = 'taku-o/vim-toggle'

[[plugins]]
repo = 'h1mesuke/unite-outline'

[[plugins]]
repo = 'h1mesuke/vim-alignta'

[[plugins]]
repo = 'ujihisa/unite-locate'

[[plugins]]
repo = 'ujihisa/unite-gem'

[[plugins]]
repo = 'ujihisa/shadow.vim'

[[plugins]]
repo = 'ujihisa/unite-rake'

[[plugins]]
repo = 'ujihisa/unite-colorscheme'

[[plugins]]
repo = 'tacroe/unite-mark'

[[plugins]]
repo = 'sgur/unite-qf'

[[plugins]]
repo = 'choplin/unite-vim_hacks'

[[plugins]]
repo = 'koron/chalice'

[[plugins]]
repo = 'tyru/open-browser.vim'

[[plugins]]
repo = 'othree/html5.vim'

[[plugins]]
repo = 'kana/vim-textobj-user'

[[plugins]]
repo = 'kana/vim-textobj-indent'

[[plugins]]
repo = 'tsukkee/unite-tag'

[[plugins]]
repo = 'bitc/vim-bad-whitespace'

[[plugins]]
repo = 'pasela/unite-webcolorname'

[[plugins]]
repo = 'taichouchou2/alpaca_powertabline'

[[plugins]]
repo = 'Lokaltog/powerline'

[[plugins]]
repo = 'bling/vim-airline'

[[plugins]]
repo = 't9md/vim-surround_custom_mapping'

[[plugins]]
repo = 'nelstrom/vim-qargs'

[[plugins]]
repo = 'nelstrom/vim-visual-star-search'

[[plugins]]
repo = 'groenewege/vim-less'

[[plugins]]
repo = 'osyo-manga/vim-over'

[[plugins]]
repo = 'AndrewRadev/linediff.vim'

[[plugins]]
repo = 'itchyny/calendar.vim'

[[plugins]]
repo = 'kannokanno/previm'

[[plugins]]
repo = 'tommcdo/vim-exchange'

[[plugins]]
repo = 'rizzatti/funcoo.vim'

[[plugins]]
repo = 'rizzatti/dash.vim'

[[plugins]]
repo = 'tejr/vim-tmux'

[[plugins]]
repo = 'altercation/vim-colors-solarized'

[[plugins]]
repo = 'rbtnn/rabbit-ui.vim'

[[plugins]]
repo = 'matchit.zip'

[[plugins]]
repo = 'JavaDecompiler.vim'

[[plugins]]
repo = 'SQLUtilities'

[[plugins]]
repo = 'svn-diff.vim'

[[plugins]]
repo = 'wombat256.vim'

[[plugins]]
repo = 'yanktmp.vim'

[[plugins]]
repo = 'Align'

[[plugins]]
repo = 'DirDiff.vim'

[[plugins]]
repo = 'vcscommand.vim'

