[[plugins]]
repo = 'vim-jp/vimdoc-ja'

[[plugins]]
repo = 'Shougo/neocomplcache'

[[plugins]]
repo = 'Shougo/neomru.vim'

[[plugins]]
repo = 'Shougo/unite.vim'

[[plugins]]
repo = 'Shougo/vimproc'

  [plugins.build]
    windows = 'tools\\update-dll-mingw'
    cygwin = 'make -f make_cygwin.mak'
    mac = 'make -f make_mac.mak'
    unix = 'make -f make_unix.mak'

[[plugins]]
repo = 'mattn/webapi-vim'

[[plugins]]
repo = 'plasticboy/vim-markdown'

[[plugins]]
repo = 'rgo/taglist.vim'

[[plugins]]
repo = 'scrooloose/syntastic'

[[plugins]]
repo = 'thinca/vim-unite-history'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'tpope/vim-unimpaired'

[[plugins]]
repo = 'tpope/vim-abolish'

[[plugins]]
repo = 'tpope/vim-repeat'

[[plugins]]
repo = 'h1mesuke/vim-alignta'

[[plugins]]
repo = 'tacroe/unite-mark'

[[plugins]]
repo = 'tyru/open-browser.vim'

[[plugins]]
repo = 'othree/html5.vim'

[[plugins]]
repo = 'kana/vim-textobj-user'

[[plugins]]
repo = 'kana/vim-textobj-indent'

[[plugins]]
repo = 'tsukkee/unite-tag'

[[plugins]]
repo = 'bitc/vim-bad-whitespace'

#[[plugins]]
#repo = 'pasela/unite-webcolorname'

[[plugins]]
repo = 'taichouchou2/alpaca_powertabline'

[[plugins]]
repo = 'Lokaltog/powerline'

[[plugins]]
repo = 'bling/vim-airline'

[[plugins]]
repo = 't9md/vim-surround_custom_mapping'

[[plugins]]
repo = 'nelstrom/vim-qargs'

[[plugins]]
repo = 'nelstrom/vim-visual-star-search'

[[plugins]]
repo = 'groenewege/vim-less'

#[[plugins]]
#repo = 'osyo-manga/vim-over'

[[plugins]]
repo = 'AndrewRadev/linediff.vim'

[[plugins]]
repo = 'itchyny/calendar.vim'

[[plugins]]
repo = 'kannokanno/previm'

[[plugins]]
repo = 'tejr/vim-tmux'

[[plugins]]
repo = 'altercation/vim-colors-solarized'

[[plugins]]
repo = 'm-kat/aws-vim'

[[plugins]]
repo = 'matchit.zip'

[[plugins]]
repo = 'JavaDecompiler.vim'

[[plugins]]
repo = 'SQLUtilities'

[[plugins]]
repo = 'svn-diff.vim'

[[plugins]]
repo = 'wombat256.vim'

[[plugins]]
repo = 'yanktmp.vim'

[[plugins]]
repo = 'DirDiff.vim'

[[plugins]]
repo = 'vcscommand.vim'

[[plugins]]
repo = 'hail2u/vim-css3-syntax'

[[plugins]]
repo = 'perlcritic-compiler-script'

[[plugins]]
repo = 'martintreurnicht/vim-gradle.git'

[[plugins]]
repo = 'elzr/vim-json'

[[plugins]]
repo = 'petdance/vim-perl'

[[plugins]]
repo = 'cakebaker/scss-syntax.vim'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'einars/js-beautify'

[[plugins]]
repo = 'vim-ruby/vim-ruby'

[[plugins]]
repo = 'cespare/vim-toml'

