[[plugins]]
repo = 'Shougo/vimfiler'
explorer = 1
on_map = '<Plug>'

[[plugins]]
repo = 'thinca/vim-quickrun'

[[plugins]]
repo = 'Shougo/neosnippet'

[[plugins]]
repo = 'Shougo/vimshell'

[[plugins]]
repo = 'tpope/vim-endwise'
on_ft = 'ruby'

[[plugins]]
repo = 'tpope/vim-rails'
on_ft = 'ruby'

[[plugins]]
repo = 'thinca/vim-ref'
on_ft = 'ruby'

[[plugins]]
repo = 'janx/vim-rubytest'
on_ft = 'ruby'

[[plugins]]
repo = 'mattn/emmet-vim'
on_ft = 'html'

[[plugins]]
repo = 'maksimr/vim-jsbeautify'
on_ft = 'javascript'

