[[plugins]]
repo = 'Shougo/vimfiler'
explorer = 1
on_map = '<Plug>'

[[plugins]]
repo = 'thinca/vim-quickrun'

[[plugins]]
repo = 'Shougo/neosnippet'

[[plugins]]
repo = "Shougo/neosnippet-snippets"

[[plugins]]
repo = 'sjl/gundo.vim'

[[plugins]]
repo = 'rking/ag.vim'

[[plugins]]
repo = 'Shougo/vimshell'

[[plugins]]
repo = 'tpope/vim-endwise'
on_ft = 'ruby'

[[plugins]]
repo = 'tpope/vim-rails'
on_ft = 'ruby'

[[plugins]]
repo = 'thinca/vim-ref'
on_ft = 'ruby'

[[plugins]]
repo = 'janx/vim-rubytest'
on_ft = 'ruby'

[[plugins]]
repo = 'vim-ruby/vim-ruby'
on_ft = 'ruby'

[[plugins]]
repo = 'mattn/emmet-vim'
on_ft = 'html'

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]]
repo = 'petdance/vim-perl'
on_ft = 'perl'

[[plugins]]
repo = 'perlcritic-compiler-script'
on_ft = 'perl'

[[plugins]]
repo = 'hail2u/vim-css3-syntax'
on_ft = 'css'

[[plugins]]
repo = 'cakebaker/scss-syntax.vim'
on_ft = 'scss'

[[plugins]]
repo = 'einars/js-beautify'
on_ft = 'javascript'

[[plugins]]
repo = 'maksimr/vim-jsbeautify'
on_ft = 'javascript'

[[plugins]]
repo = 'elzr/vim-json'
on_ft = 'json'

[[plugins]]
repo = 'martintreurnicht/vim-gradle.git'
on_ft = 'groovy'

