[[plugins]]
repo = 'Shougo/vimfiler'
explorer = 1
on_map = '<Plug>'

[[plugins]]
repo = 'thinca/vim-quickrun'

[[plugins]]
repo = 'Shougo/neosnippet'

[[plugins]]
repo = 'tpope/vim-endwise'
on_ft = 'ruby'

[[plugins]]
repo = 'tpope/vim-rails'
on_ft = 'ruby'

[[plugins]]
repo = 'mattn/emmet-vim'
on_ft = 'html'

[[plugins]]
repo = 'vim-scripts/SQLUtilities'
on_ft = 'sql'

[[plugins]]
repo = 'mattn/vim-sqlfmt'
on_ft = 'sql'

[[plugins]]
repo = 'maksimr/vim-jsbeautify'
on_ft = 'javascript'

